/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package inventory_frames;


import java.sql.*;
import javax.swing.JOptionPane;

public class create_form extends javax.swing.JFrame {

   private String name;
   private int code;
   private int quantity;
   private float price;
    public create_form() {
        initComponents();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_Panel = new javax.swing.JPanel();
        create_lbl = new javax.swing.JLabel();
        price_lbl = new javax.swing.JLabel();
        quantity_lbl = new javax.swing.JLabel();
        productCode_lbl = new javax.swing.JLabel();
        productName_lbl = new javax.swing.JLabel();
        cancel_btn = new javax.swing.JButton();
        create_btn = new javax.swing.JButton();
        productName_field = new javax.swing.JTextField();
        productCode_field = new javax.swing.JTextField();
        quantity_field = new javax.swing.JTextField();
        price_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(480, 250));

        main_Panel.setBackground(new java.awt.Color(153, 153, 153));
        main_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        create_lbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        create_lbl.setForeground(new java.awt.Color(255, 255, 255));
        create_lbl.setText("Create");
        main_Panel.add(create_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        price_lbl.setForeground(new java.awt.Color(255, 255, 255));
        price_lbl.setText("Price");
        main_Panel.add(price_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        quantity_lbl.setForeground(new java.awt.Color(255, 255, 255));
        quantity_lbl.setText("Quantity");
        main_Panel.add(quantity_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        productCode_lbl.setForeground(new java.awt.Color(255, 255, 255));
        productCode_lbl.setText("Product Code");
        main_Panel.add(productCode_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        productName_lbl.setForeground(new java.awt.Color(255, 255, 255));
        productName_lbl.setText("Product Name");
        main_Panel.add(productName_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        cancel_btn.setBackground(new java.awt.Color(153, 153, 153));
        cancel_btn.setForeground(new java.awt.Color(255, 255, 255));
        cancel_btn.setText("Cancel");
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });
        main_Panel.add(cancel_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        create_btn.setBackground(new java.awt.Color(153, 153, 153));
        create_btn.setForeground(new java.awt.Color(255, 255, 255));
        create_btn.setText("Create");
        create_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_btnActionPerformed(evt);
            }
        });
        main_Panel.add(create_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));
        main_Panel.add(productName_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 120, -1));
        main_Panel.add(productCode_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 100, -1));
        main_Panel.add(quantity_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 80, -1));
        main_Panel.add(price_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        dispose();
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void create_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_btnActionPerformed
        String pName = productName_field.getText();
        int pCode = Integer.parseInt(productCode_field.getText());
        int pQuantity = Integer.parseInt(quantity_field.getText());
        float pPrice = Float.parseFloat(price_field.getText());
        name = pName;
        code = pCode;
        quantity = pQuantity;
        price = pPrice; 
        addData();
        dispose();
    }//GEN-LAST:event_create_btnActionPerformed
    public String getName() {return name;}
    public int getCode() { return code;}
    public int getQuantity() {return quantity;}
    public float getPrice() { return price;}
    public boolean checkInput() {
        if(productName_field.getText() == null) {
            return false;
        }
        else {
            try {
            Float.parseFloat(price_field.getText());
            return true;
        } catch(Exception e) {System.out.println("checkI Error: " + e); return false; }
       }
    }
    public void addData() {
        if(checkInput() == true) {
            try {
                Connection conn = new mysqlConnection().getConnection();
                PreparedStatement ps = conn.prepareStatement("INSERT INTO product(pName, "
                                         + "pCode, pQuantity, pPrice) "
                                         + "VALUES(?, ?, ?, ?) "); 
                ps.setString(1, productName_field.getText());
                ps.setString(2, productCode_field.getText());
                ps.setString(3, quantity_field.getText());
                ps.setString(4, price_field.getText());
                ps.executeUpdate();
                dispose();
                    
                System.out.println("Product Added!");
            }catch(Exception e) { System.out.println("getData error: " + e);}
    }else {JOptionPane.showMessageDialog(null, "one or more field are empty");}
        System.out.println(productName_field.getText() + "\n" + productCode_field.getText() );
  }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(create_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(create_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(create_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(create_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new create_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_btn;
    private javax.swing.JButton create_btn;
    private javax.swing.JLabel create_lbl;
    private javax.swing.JPanel main_Panel;
    private javax.swing.JTextField price_field;
    private javax.swing.JLabel price_lbl;
    private javax.swing.JTextField productCode_field;
    private javax.swing.JLabel productCode_lbl;
    private javax.swing.JTextField productName_field;
    private javax.swing.JLabel productName_lbl;
    private javax.swing.JTextField quantity_field;
    private javax.swing.JLabel quantity_lbl;
    // End of variables declaration//GEN-END:variables

}
